language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build
dist: xenial
os: linux
deploy:
  strategy: git
  provider: pages
  local_dir: src/.vuepress/dist
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master