language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build
dist: xenial
os: linux
deploy:
  strategy: git
  provider: pages
  local_dir: src/.vuepress/dist
  token: $GITHUB_TOKEN
  repo: braincogs.github.io
  keep_history: true
  target-branch: master
  on:
    branch: master