import comp from "/Users/jl4459/Documents/Work/Princeton/BRAIN CoGS/VRrigs-documentation/.vuepress/.temp/pages/software/automation_pipeline.html.vue"
const data = JSON.parse("{\"path\":\"/software/automation_pipeline.html\",\"title\":\"Ephys/Imaging Automation Pipeline\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Ephys/Imaging Automation Pipeline\",\"lang\":\"en-US\"},\"headers\":[{\"level\":2,\"title\":\"Initial configuration\",\"slug\":\"initial-configuration\",\"link\":\"#initial-configuration\",\"children\":[]},{\"level\":2,\"title\":\"Automation GUI \\\"regular use\\\" Manual\",\"slug\":\"automation-gui-regular-use-manual\",\"link\":\"#automation-gui-regular-use-manual\",\"children\":[{\"level\":3,\"title\":\"Default use case\",\"slug\":\"default-use-case\",\"link\":\"#default-use-case\",\"children\":[]}]},{\"level\":2,\"title\":\"\\\"Advanced\\\" (select parameters) use case\",\"slug\":\"advanced-select-parameters-use-case\",\"link\":\"#advanced-select-parameters-use-case\",\"children\":[{\"level\":3,\"title\":\"On section 1:\",\"slug\":\"on-section-1\",\"link\":\"#on-section-1\",\"children\":[]},{\"level\":3,\"title\":\"On section 2:\",\"slug\":\"on-section-2\",\"link\":\"#on-section-2\",\"children\":[]}]},{\"level\":2,\"title\":\"Monitor jobs\",\"slug\":\"monitor-jobs\",\"link\":\"#monitor-jobs\",\"children\":[{\"level\":3,\"title\":\"Track status\",\"slug\":\"track-status\",\"link\":\"#track-status\",\"children\":[]}]},{\"level\":2,\"title\":\"Create new sets of processing parameters for recordings\",\"slug\":\"create-new-sets-of-processing-parameters-for-recordings\",\"link\":\"#create-new-sets-of-processing-parameters-for-recordings\",\"children\":[{\"level\":3,\"title\":\"Create new Processing parameters (algorithm pararms)\",\"slug\":\"create-new-processing-parameters-algorithm-pararms\",\"link\":\"#create-new-processing-parameters-algorithm-pararms\",\"children\":[]},{\"level\":3,\"title\":\"Create new preprocessing parameters (a single step on preprocessing list)\",\"slug\":\"create-new-preprocessing-parameters-a-single-step-on-preprocessing-list\",\"link\":\"#create-new-preprocessing-parameters-a-single-step-on-preprocessing-list\",\"children\":[]},{\"level\":3,\"title\":\"On section 0:\",\"slug\":\"on-section-0-1\",\"link\":\"#on-section-0-1\",\"children\":[]},{\"level\":3,\"title\":\"On section 1b:\",\"slug\":\"on-section-1b\",\"link\":\"#on-section-1b\",\"children\":[]},{\"level\":3,\"title\":\"Create new preprocessing parameters list (a set of preprocessing paramaters)\",\"slug\":\"create-new-preprocessing-parameters-list-a-set-of-preprocessing-paramaters\",\"link\":\"#create-new-preprocessing-parameters-list-a-set-of-preprocessing-paramaters\",\"children\":[]},{\"level\":3,\"title\":\"On section 0:\",\"slug\":\"on-section-0-2\",\"link\":\"#on-section-0-2\",\"children\":[]},{\"level\":3,\"title\":\"On section 1c:\",\"slug\":\"on-section-1c\",\"link\":\"#on-section-1c\",\"children\":[]}]}],\"git\":{},\"filePathRelative\":\"software/automation_pipeline.md\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
