import comp from "/Users/jl4459/Documents/Work/Princeton/BRAIN CoGS/VRrigs-documentation/.vuepress/.temp/pages/software/db_analysis.html.vue"
const data = JSON.parse("{\"path\":\"/software/db_analysis.html\",\"title\":\"How to use DB (tips, tricks and more)\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"How to use DB (tips, tricks and more)\",\"lang\":\"en-US\"},\"headers\":[{\"level\":2,\"title\":\"MATLAB\",\"slug\":\"matlab\",\"link\":\"#matlab\",\"children\":[{\"level\":3,\"title\":\"Prerequesites\",\"slug\":\"prerequesites\",\"link\":\"#prerequesites\",\"children\":[]},{\"level\":3,\"title\":\"Recommended tutorial\",\"slug\":\"recommended-tutorial\",\"link\":\"#recommended-tutorial\",\"children\":[]},{\"level\":3,\"title\":\"Useful scripts and functions for reseacher general use:\",\"slug\":\"useful-scripts-and-functions-for-reseacher-general-use\",\"link\":\"#useful-scripts-and-functions-for-reseacher-general-use\",\"children\":[]},{\"level\":3,\"title\":\"Read behavior file:\",\"slug\":\"read-behavior-file\",\"link\":\"#read-behavior-file\",\"children\":[]},{\"level\":3,\"title\":\"Get behavior file location (local & for spock/scotty)\",\"slug\":\"get-behavior-file-location-local-for-spock-scotty\",\"link\":\"#get-behavior-file-location-local-for-spock-scotty\",\"children\":[]},{\"level\":3,\"title\":\"get_full_trial_data with SpatialTimeBlobs\",\"slug\":\"get-full-trial-data-with-spatialtimeblobs\",\"link\":\"#get-full-trial-data-with-spatialtimeblobs\",\"children\":[]},{\"level\":3,\"title\":\"get stats from session\",\"slug\":\"get-stats-from-session\",\"link\":\"#get-stats-from-session\",\"children\":[]},{\"level\":3,\"title\":\"get behaviorfile as db\",\"slug\":\"get-behaviorfile-as-db\",\"link\":\"#get-behaviorfile-as-db\",\"children\":[]},{\"level\":3,\"title\":\"get time from iteration variable\",\"slug\":\"get-time-from-iteration-variable\",\"link\":\"#get-time-from-iteration-variable\",\"children\":[]},{\"level\":3,\"title\":\"plot framerate frequency sessions\",\"slug\":\"plot-framerate-frequency-sessions\",\"link\":\"#plot-framerate-frequency-sessions\",\"children\":[]},{\"level\":3,\"title\":\"plot framerate frequency levels and rigs\",\"slug\":\"plot-framerate-frequency-levels-and-rigs\",\"link\":\"#plot-framerate-frequency-levels-and-rigs\",\"children\":[]},{\"level\":3,\"title\":\"plot velocity sessions\",\"slug\":\"plot-velocity-sessions\",\"link\":\"#plot-velocity-sessions\",\"children\":[]},{\"level\":3,\"title\":\"get path table\",\"slug\":\"get-path-table\",\"link\":\"#get-path-table\",\"children\":[]},{\"level\":3,\"title\":\"Common errors and troubleshooting\",\"slug\":\"common-errors-and-troubleshooting\",\"link\":\"#common-errors-and-troubleshooting\",\"children\":[]}]},{\"level\":2,\"title\":\"PYTHON\",\"slug\":\"python\",\"link\":\"#python\",\"children\":[{\"level\":3,\"title\":\"Common errors and troubleshooting\",\"slug\":\"common-errors-and-troubleshooting-1\",\"link\":\"#common-errors-and-troubleshooting-1\",\"children\":[]}]}],\"git\":{},\"filePathRelative\":\"software/db_analysis.md\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
