name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 22

    - name: Install Dependencies
      run: yarn

    - name: Build VuePress
      run: yarn build

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: .vuepress/dist
        target_repo: BRAINCOGS/braincogs.github.io
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
